#!/usr/bin/env python3
"""Generate Zola art pages from static/assets/art/art.json.

The JSON file is the single source of truth for the art gallery (same pattern
as the music playlist's static/assets/music/credits.json). For every entry in
the `"art"` array this script writes one `content/art/<key>/index.md` page
whose front matter mirrors the artwork's metadata. It is idempotent: files are
only rewritten when their content actually changes, so the build.sh watch loop
converges instead of looping. Pages whose entry was removed from the JSON are
pruned.

Workflow to publish a new artwork:
  1. Drop the image file(s) into static/assets/art/<key>/.
  2. Add one entry to the `"art"` array in static/assets/art/art.json.
  3. Run ./build.sh.
"""

from __future__ import annotations

import json
import re
import sys
import urllib.parse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
META = ROOT / "static" / "assets" / "art" / "art.json"
ART_DIR = ROOT / "static" / "assets" / "art"
OUT_DIR = ROOT / "content" / "art"

GENERATED = "# generated by scripts/generate_art.py; edit static/assets/art/art.json"

RESET = "\033[0m"
GREEN = "\033[32m"
CYAN = "\033[36m"
YELLOW = "\033[33m"
RED = "\033[31m"


def log_ok(msg: str) -> None:
    print(f"  {GREEN}[OK]{RESET} {msg}")


def log_warn(msg: str) -> None:
    print(f"  {YELLOW}[WARN]{RESET} {msg}", file=sys.stderr)


def log_err(msg: str) -> None:
    print(f"  {RED}[ERROR]{RESET} {msg}", file=sys.stderr)


def log_info(msg: str) -> None:
    print(f"  {CYAN}[INFO]{RESET} {msg}")


def slugify(value: str) -> str:
    value = re.sub(r"[^a-z0-9]+", "-", value.strip().lower()).strip("-")
    return value


def to_roman(num: int) -> str:
    values = [
        (1000, "M"), (900, "CM"), (500, "D"), (400, "CD"),
        (100, "C"), (90, "XC"), (50, "L"), (40, "XL"),
        (10, "X"), (9, "IX"), (5, "V"), (4, "IV"), (1, "I"),
    ]
    out = []
    for value, numeral in values:
        while num >= value:
            out.append(numeral)
            num -= value
    return "".join(out)


def toml_string(value) -> str:
    out = []
    for ch in str(value):
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20:
            out.append("\\u%04X" % ord(ch))
        else:
            out.append(ch)
    return '"%s"' % "".join(out)


def render_page(entry: dict, defaults: dict, index: int) -> tuple[str, str]:
    """Return (output relative path, file contents) for one artwork."""
    key = slugify(str(entry["key"]))
    name_en = str(entry.get("name_en") or entry.get("name") or key)
    name_pt = str(entry.get("name_pt") or name_en)
    desc_en = str(entry.get("description_en") or "")
    desc_pt = str(entry.get("description_pt") or desc_en)
    image = str(entry.get("image") or "")
    dimensions = str(entry.get("dimensions") or entry.get("size") or defaults.get("dimensions") or defaults.get("size") or "")
    technique_en = str(entry.get("technique_en") or entry.get("technique") or "")
    technique_pt = str(entry.get("technique_pt") or technique_en)
    date = str(entry.get("date") or entry.get("year") or "")
    date_en = str(entry.get("date_en") or date)
    date_pt = str(entry.get("date_pt") or date_en)
    support = str(entry.get("support") or entry.get("support") or "")
    support_en = str(entry.get("support_en") or entry.get("support_en") or support)
    support_pt = str(entry.get("support_pt") or entry.get("support_pt") or support_en)
    license = str(entry.get("license") or defaults.get("license") or "")
    weight = int(entry.get("weight", index + 1))
    draft = "true" if entry.get("draft") else "false"

    wide = entry.get("wide") or False

    year_match = re.search(r"\b(\d{4})\b", date_en)
    roman_year = to_roman(int(year_match.group(1))) if year_match else ""

    image_url = "/assets/art/%s/%s" % (urllib.parse.quote(key), urllib.parse.quote(image))

    body = [
        "+++",
        GENERATED,
        "title = %s" % toml_string(name_en),
        "description = %s" % toml_string(desc_en),
        "weight = %d" % weight,
        "draft = %s" % draft,
        "",
        "[extra]",
        "image = %s" % toml_string(image_url),
    ]
    if wide:
        body.append("wide = true")
    body += [
        "name_en = %s" % toml_string(name_en),
        "name_pt = %s" % toml_string(name_pt),
        "description_en = %s" % toml_string(desc_en),
        "description_pt = %s" % toml_string(desc_pt),
        "dimensions = %s" % toml_string(dimensions),
        "technique_en = %s" % toml_string(technique_en),
        "technique_pt = %s" % toml_string(technique_pt),
        "date_en = %s" % toml_string(date_en),
        "date_pt = %s" % toml_string(date_pt),
        "roman_year = %s" % toml_string(roman_year),
        "support_en = %s" % toml_string(support_en),
        "support_pt = %s" % toml_string(support_pt),
        "license = %s" % toml_string(license),
        "+++",
    ]
    rel_path = OUT_DIR / key / "index.md"
    return rel_path.relative_to(ROOT).as_posix(), "\n".join(body) + "\n"


def prune_orphans(keys: set[str], changed: set[str]) -> None:
    for child in OUT_DIR.iterdir():
        if not child.is_dir() or child.name in keys:
            continue
        index = child / "index.md"
        if not index.is_file():
            continue
        if GENERATED not in index.read_text(encoding="utf-8"):
            continue
        for victim in child.iterdir():
            try:
                if victim.is_file():
                    victim.unlink()
            except OSError as exc:
                log_warn(f"Could not remove {victim}: {exc}")
        try:
            index.unlink()
        except OSError:
            pass
        try:
            child.rmdir()
            log_info(f"Pruned {child.relative_to(ROOT).as_posix()}/")
        except OSError:
            log_warn(f"Could not remove leftover {child}")
        changed.add("prune")


def main() -> int:
    if not META.is_file():
        log_warn(f"{META.relative_to(ROOT)} Missing — No art pages generated.")
        return 0

    with META.open(encoding="utf-8") as fh:
        data = json.load(fh)

    entries = data.get("art") or []
    if not isinstance(entries, list):
        log_err(f"`Art` in {META.relative_to(ROOT)} must be an array.")
        return 1
    defaults = data.get("defaults") or {}
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    written = 0
    keys: set[str] = set()
    seen: set[str] = set()
    changed: set[str] = set()

    for index, entry in enumerate(entries):
        if not isinstance(entry, dict):
            log_warn("Non-object entry in art array; skipped.")
            continue
        raw_key = str(entry.get("key") or "").strip()
        if not raw_key:
            log_warn("Artwork entry missing `key`; skipped.")
            continue
        key = slugify(raw_key)
        if key in seen:
            log_warn(f"Duplicate key `{key}` in art.json; skipped.")
            continue
        keys.add(key)
        seen.add(key)
        rel_path, contents = render_page(entry, defaults, index)

        image_name = str(entry.get("image") or "")
        if image_name:
            image_file = ART_DIR / key / image_name
            if not image_file.is_file():
                log_warn(f"Missing image {image_file.relative_to(ROOT)}")

        out_file = ROOT / rel_path
        out_file.parent.mkdir(parents=True, exist_ok=True)
        old = out_file.read_text(encoding="utf-8") if out_file.is_file() else None
        if old != contents:
            out_file.write_text(contents, encoding="utf-8")
            written += 1
            changed.add(rel_path)

    prune_orphans(keys, changed)

    total = len(seen)
    if written:
        log_ok(f"Generated/updated {written} art page(s) from {total} entr{'' if total == 1 else 'ies'} → content/art/")
    if not changed:
        log_ok(f"Art pages up to date ({total} entr{'' if total == 1 else 'ies'})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
